language: ruby

rvm:
  - 2.6.5

services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -d chitter_test 'CREATE TABLE users(id SERIAL PRIMARY KEY, username VARCHAR(60), name VARCHAR(60), email VARCHAR(60), password VARCHAR(140));'
  - psql -d chitter_test 'ALTER TABLE users ADD CONSTRAINT unique_email UNIQUE (email);
  - psql -d chitter_test ALTER TABLE users ADD CONSTRAINT unique_username UNIQUE (username);'
  - psql -d chitter_test 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, text VARCHAR(255), created_at TIMESTAMP DEFAULT NOW(), user_id INTEGER REFERENCES users (id));'
  
script:
  - bundle exec rspec
