language: ruby

rvm:
  - 2.6.5

services:
  - postgresql


before_script:
  - psql -c 'CREATE DATABASE chitter_test;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - bundle exec rspec
