language: ruby

rvm:
  - 2.6.5

services:
  - postgresql

  addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4


before_script:
  - psql -c 'CREATE DATABASE chitter_test;' -U postgres

script:
  - bundle exec rspec
