language: ruby

rvm:
  - 2.6.5

services:
  - postgresql

before_install:
  - sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'CREATE DATABASE chitter_test;' -U postgres

script:
  - mkdir -p spec && bundle exec rspec spec